### ISSUE TITLE
[Question] Clarification on BIND configuration

### ISSUE THREAD

**Issue by steckel** [SFTtech/sftdyn#7]
This project references BIND needing be "configured to serve the updatable zone." I am not experienced with BIND and the tutorials I have found are quite diverse. Are there any resources or more specific instructions you could offer? (e.g. Should I be configuring an authoritative DNS server, a forwarding server or what not?) Thank you.

**Comment by TheJJ** [comment]
Hi! You have to serve a regular authoritative zone that is delegated to this DNS-server. I recommend to create a zone `dyn.yourdomain.lol` and delegate it (with a `SRV` record) to the DNS-server that hosts sftdyn and the `dyn` zone.

`sftdyn` will add entries to this zone, so whenever the server is queried for e.g. `myhost.dyn.yourdomain.lol`, the correct IP will be returned as answer.

We have some documentation in the repo about the setup, did you read it already?

Otherwise, I would suggest that you read e.g. [the arch wiki](https://wiki.archlinux.org/index.php/BIND#A_configuration_template_for_running_a_domain).
The records in this domain will then be updated by sftdyn. Records don't need to exist, sftdyn can also create totally new entries.

**Comment by TheJJ** [comment]
I'll close this for now. If you have any other question, please notify us again.
