### ISSUE TITLE
Config File

### ISSUE THREAD

**Issue by jakenology** [SFTtech/sftdyn#8]
How do I set up the config file?
For the example host:
What would I enter for the username and password, etc...

What if I want multiple clients, how does that go in that dict?

Please help.

I'm at dyn.bluejayit.com if that helps

**Comment by TheJJ** [comment]
The config file is actually a Python file, so you just use Python syntax.
If you have a working `nsupdate` on your server, you create a mapping between client identifiers and the hostname to update.

The docs say:
``` python
# map "urlsuffix" => "host to update with nsupdate"
```

That means: when `urlsuffix` is called, we update the hostname on the right side to the IP that did the request. `urlsuffix` is the part behind the hostname, i.e. http://yoursftdynserver/$urlsuffix
Example:

``` python
clients = {
    "example": "somehost.yourzone.lol",
}
```

Then a query to `http://yoursftdynserver/example` will update `somehost.yourzone.lol` to the ip the query came from.

In order to make the URLs more secret, we recommend to create them in a more complicated way:

``` python
clients = {
    "?hostname=somehost.yourzone.lol&secret=42secret1337": "somehost.yourzone.lol",
    "anothercustomhostidentifier": "anotherhost.yourzone.lol",
}
```

The lookup is the same: When you `GET` http://yoursftdynserver/?hostname=somehost.yourzone.lol&secret=42secret1337, this is resolved to `somehost.yourzone.lol` because of the client-definition-config, and the IP is updated accordingly.

Does that help?

**Comment by TheJJ** [comment]
I'll close this now, please report back if you need additional help, or come by in our chatroom.
